"""add collection table

Revision ID: 6f36c3d925fd
Revises: 1992f64daec2
Create Date: 2025-10-31 21:28:33.297360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f36c3d925fd'
down_revision: Union[str, Sequence[str], None] = '1992f64daec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('collections_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('collections_pkey')),
    sa.UniqueConstraint('name', name=op.f('collections_name_key'))
    )
    op.create_index(op.f('collections_created_at_idx'), 'collections', ['created_at'], unique=False)
    op.create_table('collection_dish',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('collection_dish_collection_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name=op.f('collection_dish_dish_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'dish_id', name=op.f('collection_dish_pkey')),
    comment='收藏-菜品 中间表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_dish')
    op.drop_index(op.f('collections_created_at_idx'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
